# Generated by Django 3.1.7 on 2021-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('janr', models.CharField(choices=[('Jangari', 'Jangari'), ('Fantastik', 'Fantastik'), ('Tarixiy', 'Tarixiy'), ('Detektiv', 'Detektiv'), ('Kamediya', 'Kamediya'), ('Drama', 'Drama'), ('Multfilm', 'Multfilm')], default='Kamediya', max_length=15)),
                ('narxi', models.FloatField(default=0)),
                ('yili', models.IntegerField(verbose_name='Ishlangan yili')),
                ('davomiyligi', models.TimeField()),
                ('movie', models.FileField(upload_to='movie', verbose_name='Video fayli')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sanasi')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name="Eng ko'p sotilgan kino")),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
    ]
