# Generated by Django 3.1.7 on 2021-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0003_auto_20210303_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avtor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
