# Generated by Django 3.1.7 on 2021-03-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0004_movie_avtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='davomiyligi',
            field=models.CharField(max_length=10),
        ),
    ]
